repos:
  - repo: local
    hooks:
      - id: black
        name: Format with black
        entry: black src/
        language: system
        types: [python]
      - id: black
        name: Format main file with black
        entry: black main.py
        language: system
        types: [python]
      - id: vulture
        name: Run vulture
        entry: vulture . --exclude ".venv/_,**/site-packages/_"
        language: system
        types: [python]
      - id: prospector
        name: Run prospector
        entry: prospector
        language: system
        types: [python]
