output-format: grouped

strictness: veryhigh
doc-warnings: true
test-warnings: true
member-warnings: true

ignore-patterns:
  - ^\.tox/.*
  - ^\.venv/.*
  - ^\.git/.*
  - ^build/.*
  - ^dist/.*

pylint:
  disable:
    - bad-continuation
    - missing-docstring
    - wrong-import-position
    - wrong-import-order
    - broad-exception-caught
    - astroid-error
    - invalid-name
    - unused-variable
    - ungrouped-imports
  enable:
    - useless-suppression
  options:
    max-line-length: 300
    max-args: 5
    max-locals: 16
    max-returns: 6
    max-branches: 12
    max-statements: 50
    max-parents: 7
    max-attributes: 7
    min-public-methods: 1
    max-public-methods: 20

mccabe:
  options:
    max-complexity: 10

pycodestyle:
  disable:
    - E226
    - E302
    - E41
    - E501
    - E305
    - E231
    - W293
  options:
    max-line-length: 300

pydocstyle:
  disable:
    - D203
    - D212
    - D213
    - D404
    - D406
    - D407
    - D408
    - D409
    - D413

pyflakes:
  disable:
    - F401
    - F403

dodgy:
  run: true

vulture:
  run: false

frosted:
  run: true

mypy:
  run: false
  options:
    ignore-missing-imports: true
    follow-imports: skip

bandit:
  run: false
  options:
    exclude: tests

pyroma:
  run: true
