#!/bin/sh

# Format code using black
black src/
black main.py

# Run vulture to find unused code
vulture . --exclude ".venv/,**/site-packages/"

# Run prospector for linting
prospector

# # After running the checks, prompt the user for verification
# echo "Do you want to proceed with the commit? (y/n)"
# read answer
# if [ "$answer" != "y" ]; then
#     echo "Aborting commit."
#     exit 1
# fi
