import random
from datetime import datetime
import pytz
import yfinance as yf
from src.email_utils import send_email

stocks = [
    "ACSEL",
    "ADEL",
    "ADESE",
    "AEFES",
    "AFYON",
    "AGYO",
    "AKBNK",
    "AKCNS",
    "AKENR",
    "AKFGY",
    "AKGRT",
    "AKMGY",
    "AKSA",
    "AKSEN",
    "AKSGY",
    "AKSUE",
    "ALARK",
    "ALBRK",
    "ALCAR",
    "ALCTL",
    "ALGYO",
    "ALKIM",
    "ANELE",
    "ANHYT",
    "ANSGR",
    "ARCLK",
    "ARENA",
    "ARSAN",
    "ASELS",
    "ASUZU",
    "ATAGY",
    "ATEKS",
    "ATLAS",
    "ATSYH",
    "AVGYO",
    "AVHOL",
    "AVOD",
    "AVTUR",
    "AYCES",
    "AYEN",
    "AYES",
    "AYGAZ",
    "BAGFS",
    "BAKAB",
    "BALAT",
    "BANVT",
    "BASCM",
    "BEYAZ",
    "BFREN",
    "BIMAS",
    "BIZIM",
    "BJKAS",
    "BLCYT",
    "BNTAS",
    "BOSSA",
    "BRISA",
    "BRKSN",
    "BRMEN",
    "BRSAN",
    "BRYAT",
    "BSOKE",
    "BTCIM",
    "BUCIM",
    "BURCE",
    "BURVA",
    "CCOLA",
    "CELHA",
    "CEMAS",
    "CEMTS",
    "CIMSA",
    "CLEBI",
    "CMBTN",
    "CMENT",
    "COSMO",
    "CRDFA",
    "CRFSA",
    "CUSAN",
    "DAGHL",
    "DAGI",
    "DARDL",
    "DENGE",
    "DERIM",
    "DEVA",
    "DGATE",
    "DGGYO",
    "DIRIT",
    "DITAS",
    "DMSAS",
    "DOAS",
    "DOBUR",
    "DOCO",
    "DOGUB",
    "DOHOL",
    "DURDO",
    "DYOBY",
    "DZGYO",
    "ECILC",
    "ECZYT",
    "EDIP",
    "EGEEN",
    "EGGUB",
    "EGPRO",
    "EGSER",
    "EKGYO",
    "EKIZ",
    "EMKEL",
    "EMNIS",
    "ENKAI",
    "EPLAS",
    "ERBOS",
    "EREGL",
    "ERSU",
    "ESCOM",
    "ETILR",
    "ETYAT",
    "EUHOL",
    "EUKYO",
    "EUYO",
    "FENER",
    "FLAP",
    "FMIZP",
    "FRIGO",
    "FROTO",
    "GARAN",
    "GARFA",
    "GEDIK",
    "GEDZA",
    "GENTS",
    "GEREL",
    "GLBMD",
    "GLRYH",
    "GLYHO",
    "GOLTS",
    "GOODY",
    "GOZDE",
    "GRNYO",
    "GSDDE",
    "GSDHO",
    "GSRAY",
    "GUBRF",
    "HALKB",
    "HATEK",
    "HDFGS",
    "HEKTS",
    "HLGYO",
    "HURGZ",
    "ICBCT",
    "IDGYO",
    "IEYHO",
    "IHEVA",
    "IHGZT",
    "IHLAS",
    "IHYAY",
    "INDES",
    "INFO",
    "INTEM",
    "IPEKE",
    "ISBIR",
    "ISBTR",
    "ISCTR",
    "ISDMR",
    "ISFIN",
    "ISGSY",
    "ISGYO",
    "ISMEN",
    "ISYAT",
    "IZFAS",
    "IZMDC",
    "JANTS",
    "KAPLM",
    "KAREL",
    "KARSN",
    "KARTN",
    "KATMR",
    "KCHOL",
    "KENT",
    "KERVN",
    "KERVT",
    "KLGYO",
    "KLMSN",
    "KLNMA",
    "KNFRT",
    "KONYA",
    "KORDS",
    "KOZAA",
    "KOZAL",
    "KRDMA",
    "KRDMB",
    "KRDMD",
    "KRGYO",
    "KRONT",
    "KRSTL",
    "KRTEK",
    "KSTUR",
    "KUTPO",
    "KUYAS",
    "LIDFA",
    "LINK",
    "LKMNH",
    "LOGO",
    "LUKSK",
    "MAALT",
    "MAKTK",
    "MARTI",
    "MEGAP",
    "MEPET",
    "MERIT",
    "MERKO",
    "METAL",
    "METRO",
    "METUR",
    "MGROS",
    "MIPAZ",
    "MMCAS",
    "MNDRS",
    "MRGYO",
    "MRSHL",
    "MZHLD",
    "NETAS",
    "NIBAS",
    "NTHOL",
    "NUGYO",
    "NUHCM",
    "ODAS",
    "ORGE",
    "ORMA",
    "OSMEN",
    "OSTIM",
    "OTKAR",
    "OYAYO",
    "OYLUM",
    "OZGYO",
    "OZKGY",
    "OZRDN",
    "PAGYO",
    "PARSN",
    "PEGYO",
    "PENGD",
    "PETKM",
    "PETUN",
    "PGSUS",
    "PINSU",
    "PKART",
    "PKENT",
    "PNSUT",
    "POLHO",
    "POLTK",
    "PRKAB",
    "PRKME",
    "PRZMA",
    "PSDTC",
    "RAYSG",
    "RODRG",
    "RTALB",
    "RYGYO",
    "RYSAS",
    "SAHOL",
    "SAMAT",
    "SANEL",
    "SANFM",
    "SARKY",
    "SASA",
    "SAYAS",
    "SEKFK",
    "SEKUR",
    "SELEC",
    "SELGD",
    "SEYKM",
    "SILVR",
    "SISE",
    "SKBNK",
    "SKTAS",
    "SNGYO",
    "SNKRN",
    "SNPAM",
    "SODSN",
    "SONME",
    "SRVGY",
    "TATGD",
    "TAVHL",
    "TBORG",
    "TCELL",
    "TEKTU",
    "TGSAS",
    "THYAO",
    "TKFEN",
    "TKNSA",
    "TMPOL",
    "TMSN",
    "TOASO",
    "TRCAS",
    "TRGYO",
    "TSKB",
    "TSPOR",
    "TTKOM",
    "TTRAK",
    "TUCLK",
    "TUKAS",
    "TUPRS",
    "TURGG",
    "ULAS",
    "ULKER",
    "ULUSE",
    "ULUUN",
    "UMPAS",
    "USAK",
    "USAS",
    "UZERB",
    "VAKBN",
    "VAKFN",
    "VAKKO",
    "VANGD",
    "VERTU",
    "VERUS",
    "VESBE",
    "VESTL",
    "VKFYO",
    "VKGYO",
    "VKING",
    "YAPRK",
    "YATAS",
    "YAYLA",
    "YBTAS",
    "YESIL",
    "YGGYO",
    "YGYO",
    "YKBNK",
    "YONGA",
    "YUNSA",
    "YYAPI",
    "ZOREN",
]


def bist30_change():
    chosen_stock = random.choice(stocks)
    stock_code = chosen_stock + ".IS"

    tz = pytz.timezone("Europe/Istanbul")
    today_date = datetime.now(tz)
    day = today_date.strftime("%d")
    day = day[1:] if day.startswith("0") else day
    month = today_date.strftime("%B")
    turkish_month = {
        "January": "Ocak",
        "February": "Şubat",
        "March": "Mart",
        "April": "Nisan",
        "May": "Mayıs",
        "June": "Haziran",
        "July": "Temmuz",
        "August": "Ağustos",
        "September": "Eylül",
        "October": "Ekim",
        "November": "Kasım",
        "December": "Aralık",
    }[month]

    hisse = yf.Ticker(stock_code)
    hisse_data = hisse.history(period="max")
    hisse_current = hisse.info.get("currentPrice", "0")
    hisse_prev = hisse.info.get("previousClose", "0")
    hisse_current_change = ((hisse_current - hisse_prev) / hisse_prev) * 100
    hisse_current_change = round(hisse_current_change, 2)
    emo = "📈" if hisse_current_change > 0 else "📉"
    text = "yükseldi" if hisse_current_change > 0 else "düştü"
    subject = "send_bist30_stock #bist30_change"
    body = f"""🔴 #{chosen_stock} bugün %{hisse_current_change} {text}

{emo} Anlık Fiyatı: {hisse_current} \n
    """

    # print(body)
    send_email(subject, body)


if __name__ == "__main__":
    bist30_change()
